name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn

      - name: check types
        run: yarn tsc -p . --noEmit

      - name: check style and linting
        run: yarn style --check && yarn lint --max-warnings 0
