name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2.3.1

      - name: install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn

      - name: check types
        run: yarn tsc -p . --noEmit

      - name: check style and linting
        run: yarn style && yarn lint
