name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: install
        run: yarn

      - name: build
        run: PUBLIC_URL="/substitute" yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
