name: Build

on:
  push:
    branches:
      - source
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn

      - name: build
        run: PUBLIC_URL="https://thelartians.de/substitute" yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: build
          CLEAN: true
