name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: mfinelli/setup-imagemagick@v6

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: install
        run: yarn

      - name: build
        run: PUBLIC_URL="/substitute" yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true
